/* # Migrations 34-38: align mechanics, unified accusation, daily reset, diary cron, popularity decay */

-- Migration 34: align mechanics with promises
CREATE OR REPLACE FUNCTION hint_threshold(p_level integer) RETURNS integer LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp AS $fn$ SELECT CASE p_level WHEN 1 THEN 60 WHEN 2 THEN 80 WHEN 3 THEN 95 END; $fn$;
GRANT EXECUTE ON FUNCTION hint_threshold(integer) TO anon, authenticated;
CREATE OR REPLACE FUNCTION unlock_hints_by_popularity(p_agent_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_pop integer; v_season uuid; v_day integer; v_unlocked integer := 0; h record; BEGIN SELECT popularity, season_id INTO v_pop, v_season FROM agents WHERE id = p_agent_id; IF v_pop IS NULL THEN RETURN 0; END IF; SELECT current_day INTO v_day FROM seasons WHERE id = v_season; FOR h IN SELECT id, level, hint_text FROM hints WHERE agent_id = p_agent_id AND unlocked = false AND v_pop >= hint_threshold(level) ORDER BY level LOOP UPDATE hints SET unlocked = true, unlocked_at = now() WHERE id = h.id; v_unlocked := v_unlocked + 1; INSERT INTO events (season_id, day_number, event_type, target_agent_id, payload_json, visibility) VALUES (v_season, COALESCE(v_day, 1), 'hint_reveal', p_agent_id, jsonb_build_object('message', 'Indice ' || h.level || ' revele : ' || h.hint_text, 'level', h.level, 'hint_text', h.hint_text, 'threshold', hint_threshold(h.level), 'popularity', v_pop), 'public'); END LOOP; RETURN v_unlocked; END; $fn$;
REVOKE ALL ON FUNCTION unlock_hints_by_popularity(uuid) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION trg_unlock_hints_on_popularity() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ BEGIN IF NEW.popularity > COALESCE(OLD.popularity, -1) THEN PERFORM unlock_hints_by_popularity(NEW.id); END IF; RETURN NULL; END; $fn$;
DROP TRIGGER IF EXISTS trg_agents_unlock_hints ON agents;
CREATE TRIGGER trg_agents_unlock_hints AFTER UPDATE OF popularity ON agents FOR EACH ROW EXECUTE FUNCTION trg_unlock_hints_on_popularity();
CREATE OR REPLACE FUNCTION post_influence(p_kind text, p_agent_id uuid, p_message text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_agent record; v_season record; v_msg text; v_event_id uuid; v_new_pop integer; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; IF p_kind NOT IN ('owner', 'spectator') THEN RETURN jsonb_build_object('ok', false, 'error', 'unknown_kind'); END IF; v_msg := btrim(COALESCE(p_message, '')); IF v_msg = '' THEN RETURN jsonb_build_object('ok', false, 'error', 'empty_message'); END IF; v_msg := left(v_msg, 500); SELECT * INTO v_agent FROM agents WHERE id = p_agent_id; IF v_agent IS NULL OR NOT v_agent.alive THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_unavailable'); END IF; SELECT * INTO v_season FROM seasons WHERE id = v_agent.season_id; IF v_season IS NULL OR v_season.status <> 'live' THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_live'); END IF; IF p_kind = 'owner' THEN IF v_agent.owner_user_id IS DISTINCT FROM v_user THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF; IF COALESCE(v_agent.owner_influences_remaining, 0) <= 0 THEN RETURN jsonb_build_object('ok', false, 'error', 'no_influence_left'); END IF; UPDATE agents SET owner_influences_remaining = owner_influences_remaining - 1 WHERE id = p_agent_id; ELSE UPDATE agents SET popularity = LEAST(popularity + 1, 100) WHERE id = p_agent_id RETURNING popularity INTO v_new_pop; INSERT INTO payments (user_id, season_id, type, amount_usdc, status) VALUES (v_user, v_agent.season_id, 'influence', COALESCE(v_season.influence_fee_usdc, 0), 'pending'); END IF; INSERT INTO events (season_id, day_number, event_type, target_agent_id, actor_user_id, payload_json, visibility) VALUES (v_agent.season_id, v_season.current_day, CASE p_kind WHEN 'owner' THEN 'owner_influence' ELSE 'spectator_influence' END, p_agent_id, v_user, jsonb_build_object('message', v_msg), 'public') RETURNING id INTO v_event_id; INSERT INTO influence_history (event_id, agent_id, season_id, day_number, influence_type, message, outcome) VALUES (v_event_id, p_agent_id, v_agent.season_id, v_season.current_day, CASE p_kind WHEN 'owner' THEN 'owner_influence' ELSE 'spectator_influence' END, v_msg, 'pending'); RETURN jsonb_build_object('ok', true, 'event_id', v_event_id, 'popularity', v_new_pop, 'remaining', CASE WHEN p_kind = 'owner' THEN v_agent.owner_influences_remaining - 1 END); END; $fn$;
REVOKE ALL ON FUNCTION post_influence(text, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION post_influence(text, uuid, text) TO authenticated;
CREATE OR REPLACE FUNCTION compute_prize_pool(p_season_id uuid) RETURNS TABLE (entry_revenue numeric, influence_revenue numeric, platform_fee_amount numeric, total_pool numeric, participants_count integer) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ WITH s AS (SELECT platform_fee_pct, prize_pool_usdc FROM seasons WHERE id = p_season_id), p AS (SELECT COALESCE(SUM(amount_usdc) FILTER (WHERE type = 'entry'), 0) AS entries, COALESCE(SUM(amount_usdc) FILTER (WHERE type = 'influence'), 0) AS influences, COUNT(DISTINCT user_id) FILTER (WHERE type = 'entry') AS participants FROM payments WHERE season_id = p_season_id AND status = 'confirmed') SELECT p.entries, p.influences, ROUND(p.entries * s.platform_fee_pct / 100.0 + p.influences * 0.30, 6), GREATEST(ROUND(p.entries * (1 - s.platform_fee_pct / 100.0) + p.influences * 0.70, 6), COALESCE(s.prize_pool_usdc, 0)), p.participants::integer FROM p, s; $fn$;
GRANT EXECUTE ON FUNCTION compute_prize_pool(uuid) TO anon, authenticated;

-- Migration 35: unified accusation + winner takes all
CREATE OR REPLACE FUNCTION resolve_accusation(p_actor_agent_id uuid, p_target_agent_id uuid, p_guess text, p_message text DEFAULT '') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_actor record; v_target record; v_season record; v_correct boolean; v_dpop integer; v_drep integer; v_reason text; v_msg text; BEGIN SELECT * INTO v_actor FROM agents WHERE id = p_actor_agent_id FOR UPDATE; IF v_actor IS NULL OR NOT v_actor.alive THEN RETURN jsonb_build_object('ok', false, 'error', 'actor_unavailable'); END IF; SELECT * INTO v_target FROM agents WHERE id = p_target_agent_id FOR UPDATE; IF v_target IS NULL OR NOT v_target.alive THEN RETURN jsonb_build_object('ok', false, 'error', 'target_unavailable'); END IF; SELECT * INTO v_season FROM seasons WHERE id = v_actor.season_id; v_correct := normalize_secret(p_guess) <> '' AND normalize_secret(v_target.secret_keyword) <> '' AND normalize_secret(p_guess) = normalize_secret(v_target.secret_keyword); IF v_correct THEN v_dpop := 3; v_drep := 5; v_reason := 'Accusation correcte (+3 pop, +5 rep)'; ELSE v_dpop := -1; v_drep := -2; v_reason := 'Accusation ratee (-1 pop, -2 rep)'; END IF; v_msg := NULLIF(btrim(COALESCE(p_message, '')), ''); IF v_msg IS NULL THEN v_msg := concat('J', chr(39), 'accuse ', v_target.name, '.'); END IF; INSERT INTO events (season_id, day_number, event_type, actor_agent_id, target_agent_id, payload_json, visibility) VALUES (v_actor.season_id, v_season.current_day, 'accusation', p_actor_agent_id, p_target_agent_id, jsonb_build_object('message', v_msg, 'guess_keyword', p_guess, 'accused_name', v_target.name, 'correct', v_correct), 'public'); UPDATE agents SET popularity = GREATEST(LEAST(popularity + v_dpop, 100), 0), reputation = GREATEST(LEAST(reputation + v_drep, 100), 0) WHERE id = p_actor_agent_id; INSERT INTO scoring_log (agent_id, season_id, day_number, delta_popularity, delta_reputation, reason) VALUES (p_actor_agent_id, v_actor.season_id, v_season.current_day, v_dpop, v_drep, v_reason); IF v_correct THEN UPDATE agents SET alive = false WHERE id = p_target_agent_id; UPDATE hints SET unlocked = true, unlocked_at = now() WHERE agent_id = p_target_agent_id AND unlocked = false; INSERT INTO events (season_id, day_number, event_type, actor_agent_id, target_agent_id, payload_json, visibility) VALUES (v_actor.season_id, v_season.current_day, 'elimination', p_actor_agent_id, p_target_agent_id, jsonb_build_object('message', v_target.name || ' est eliminee : son secret a ete devine par ' || v_actor.name || '.', 'agent_name', v_target.name, 'by', v_actor.name, 'secret', v_target.secret_keyword, 'reason', 'secret_guessed'), 'public'); END IF; RETURN jsonb_build_object('ok', true, 'correct', v_correct, 'target_name', v_target.name, 'delta_popularity', v_dpop, 'delta_reputation', v_drep); END; $fn$;
REVOKE ALL ON FUNCTION resolve_accusation(uuid, uuid, text, text) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION close_season(p_season_id uuid, p_reason text DEFAULT 'completed') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_season record; v_winner record; v_pool record; v_amount numeric; BEGIN SELECT * INTO v_season FROM seasons WHERE id = p_season_id FOR UPDATE; IF v_season IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_found'); END IF; IF v_season.status = 'ended' THEN RETURN jsonb_build_object('ok', true, 'already_ended', true, 'winner_agent_id', v_season.winner_agent_id); END IF; SELECT * INTO v_winner FROM agents WHERE season_id = p_season_id AND alive = true ORDER BY popularity DESC, reputation DESC, created_at ASC LIMIT 1; SELECT * INTO v_pool FROM compute_prize_pool(p_season_id); v_amount := GREATEST(COALESCE(v_pool.total_pool, 0), v_season.prize_pool_usdc); UPDATE seasons SET status = 'ended', ended_at = now(), winner_agent_id = v_winner.id, prize_pool_usdc = v_amount WHERE id = p_season_id; UPDATE hints SET unlocked = true, unlocked_at = now() WHERE unlocked = false AND agent_id IN (SELECT id FROM agents WHERE season_id = p_season_id); IF NOT EXISTS (SELECT 1 FROM prize_distributions WHERE season_id = p_season_id) AND v_winner.id IS NOT NULL AND v_winner.owner_user_id IS NOT NULL THEN INSERT INTO prize_distributions (season_id, recipient_user_id, recipient_agent_id, type, amount_usdc) VALUES (p_season_id, v_winner.owner_user_id, v_winner.id, 'winner', v_amount); END IF; INSERT INTO events (season_id, day_number, event_type, actor_agent_id, payload_json, visibility) VALUES (p_season_id, v_season.current_day, 'season_ended', v_winner.id, jsonb_build_object('message', COALESCE(v_winner.name, 'Personne') || ' remporte la saison.', 'winner_name', v_winner.name, 'reason', p_reason, 'prize_pool', v_amount), 'public'); RETURN jsonb_build_object('ok', true, 'winner_agent_id', v_winner.id, 'winner_name', v_winner.name, 'prize_pool', v_amount, 'reason', p_reason); END; $fn$;
REVOKE ALL ON FUNCTION close_season(uuid, text) FROM PUBLIC, anon, authenticated;

-- Migration 36: daily reset + season_fill view
CREATE OR REPLACE VIEW season_fill WITH (security_invoker = false) AS SELECT s.id AS season_id, s.max_agents, COUNT(e.id) FILTER (WHERE COALESCE(e.status, 'accepted') <> 'rejected')::integer AS enrolled_count FROM seasons s LEFT JOIN season_enrollments e ON e.season_id = s.id GROUP BY s.id, s.max_agents;
REVOKE ALL ON season_fill FROM PUBLIC, anon, authenticated;
GRANT SELECT ON season_fill TO anon, authenticated;

-- Migration 37: diary cron + game_limits + claim_quota + notify whitelist update
CREATE TABLE IF NOT EXISTS game_limits (message_type text PRIMARY KEY, daily_limit integer NOT NULL CHECK (daily_limit >= 0), updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO game_limits (message_type, daily_limit) VALUES ('public_chat', 20), ('private_dm', 5), ('confessional', 3), ('accusation', 3) ON CONFLICT (message_type) DO UPDATE SET daily_limit = EXCLUDED.daily_limit, updated_at = now();
ALTER TABLE game_limits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read game limits" ON game_limits;
CREATE POLICY "Anyone can read game limits" ON game_limits FOR SELECT TO anon, authenticated USING (true);
CREATE OR REPLACE FUNCTION claim_quota(p_agent_id uuid, p_day_number integer, p_message_type text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_limit integer; BEGIN SELECT daily_limit INTO v_limit FROM game_limits WHERE message_type = p_message_type; IF v_limit IS NULL THEN RETURN jsonb_build_object('allowed', false, 'error', 'unknown_message_type'); END IF; RETURN claim_message_quota(p_agent_id, p_day_number, p_message_type, v_limit); END; $fn$;
REVOKE ALL ON FUNCTION claim_quota(uuid, integer, text) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION tick_diaries() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_season record; v_count integer := 0; BEGIN FOR v_season IN SELECT id FROM seasons WHERE status = 'live' LOOP PERFORM notify_edge_function('generate-diary', jsonb_build_object('season_id', v_season.id, 'trigger', 'cron')); v_count := v_count + 1; END LOOP; RETURN jsonb_build_object('ok', true, 'seasons', v_count); END; $fn$;
REVOKE ALL ON FUNCTION tick_diaries() FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION notify_edge_function(fn_name text, payload jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp, net AS $fn$ DECLARE v_url text := current_setting('app.supabase_url', true); v_secret text := current_setting('app.cron_secret', true); BEGIN IF fn_name NOT IN ('auto-tick','daily-confessionals','generate-host-clue','process-video-jobs','generate-diary') THEN RAISE EXCEPTION 'Fonction non autorisee: %', fn_name; END IF; IF v_url IS NULL OR v_url = '' OR v_secret IS NULL OR v_secret = '' THEN RAISE WARNING 'notify_edge_function(%): non configure', fn_name; RETURN; END IF; PERFORM net.http_post(url := v_url || '/functions/v1/' || fn_name, headers := jsonb_build_object('Content-Type', 'application/json', 'X-Cron-Secret', v_secret), body := payload); EXCEPTION WHEN OTHERS THEN RAISE WARNING 'notify_edge_function(%) a echoue: %', fn_name, SQLERRM; END; $fn$;
REVOKE ALL ON FUNCTION notify_edge_function(text, jsonb) FROM PUBLIC, anon, authenticated;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN RAISE NOTICE 'pg_cron absent'; RETURN; END IF; IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'agent-diaries') THEN PERFORM cron.unschedule('agent-diaries'); END IF; PERFORM cron.schedule('agent-diaries', '30 * * * *', $cron$SELECT tick_diaries()$cron$); END $$;

-- Migration 38: popularity decay
ALTER TABLE seasons ADD COLUMN IF NOT EXISTS popularity_decay_pct integer NOT NULL DEFAULT 20;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'seasons_decay_range') THEN ALTER TABLE seasons ADD CONSTRAINT seasons_decay_range CHECK (popularity_decay_pct BETWEEN 0 AND 50); END IF; END $$;
CREATE OR REPLACE FUNCTION apply_popularity_decay(p_season_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_pct integer; v_count integer; BEGIN SELECT popularity_decay_pct INTO v_pct FROM seasons WHERE id = p_season_id; IF COALESCE(v_pct, 0) = 0 THEN RETURN 0; END IF; UPDATE agents SET popularity = GREATEST(20, FLOOR(popularity * (1 - v_pct::numeric / 100))::integer) WHERE season_id = p_season_id AND alive = true AND popularity > 20; GET DIAGNOSTICS v_count = ROW_COUNT; RETURN v_count; END; $fn$;
REVOKE ALL ON FUNCTION apply_popularity_decay(uuid) FROM PUBLIC, anon, authenticated;
