/* # Migrations 29-33: DM paywall, wallet nonces, atomic quota, fix grants, admin controls */

-- Migration 29: DM paywall + cron reconfiguration
CREATE OR REPLACE VIEW events_feed WITH (security_invoker = false) AS
SELECT e.id, e.season_id, e.day_number, e.event_type, e.actor_agent_id, e.target_agent_id, e.actor_user_id, e.visibility, e.created_at, e.video_job_id,
  CASE
    WHEN e.event_type <> 'private_dm' THEN e.payload_json
    WHEN EXISTS (SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.role = 'admin') THEN e.payload_json
    WHEN EXISTS (SELECT 1 FROM agents a WHERE a.id IN (e.actor_agent_id, e.target_agent_id) AND a.owner_user_id = auth.uid()) THEN e.payload_json
    WHEN EXISTS (SELECT 1 FROM dm_reveals d WHERE d.event_id = e.id AND d.user_id = auth.uid()) THEN e.payload_json
    WHEN EXISTS (SELECT 1 FROM seasons s WHERE s.id = e.season_id AND s.status = 'ended') THEN e.payload_json
    ELSE jsonb_build_object('locked', true, 'preview', 'Un message prive a ete echange.')
  END AS payload_json
FROM events e
WHERE e.visibility = 'public' OR e.event_type = 'private_dm' OR EXISTS (SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.role = 'admin');
GRANT SELECT ON events_feed TO anon, authenticated;
UPDATE events SET visibility = 'private_admin' WHERE event_type = 'private_dm' AND visibility = 'public';
DROP POLICY IF EXISTS "Anon can see DM existence in feed" ON events;
DO $$ DECLARE v_job record; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN RAISE NOTICE 'pg_cron absent'; RETURN; END IF;
  FOR v_job IN SELECT jobname FROM cron.job WHERE jobname IN ('agent-auto-tick','host-clue-every-6h','daily-confessionals','daily-agent-hint','process-video-jobs','season-day-advance') LOOP PERFORM cron.unschedule(v_job.jobname); END LOOP;
  PERFORM cron.schedule('agent-auto-tick', '*/2 * * * *', $cron$SELECT notify_edge_function('auto-tick', jsonb_build_object('trigger', 'cron'))$cron$);
  PERFORM cron.schedule('host-clue-every-6h', '0 */6 * * *', $cron$SELECT notify_edge_function('generate-host-clue', jsonb_build_object('mode', 'random'))$cron$);
  PERFORM cron.schedule('daily-confessionals', '0 20 * * *', $cron$SELECT notify_edge_function('daily-confessionals', jsonb_build_object('trigger', 'cron'))$cron$);
  PERFORM cron.schedule('process-video-jobs', '* * * * *', $cron$SELECT notify_edge_function('process-video-jobs', jsonb_build_object('trigger', 'cron'))$cron$);
  PERFORM cron.schedule('season-day-advance', '0 * * * *', $cron$SELECT tick_all_seasons()$cron$);
END $$;

-- Migration 30: wallet nonces
CREATE TABLE IF NOT EXISTS wallet_nonces (wallet_address text PRIMARY KEY, nonce text NOT NULL, message text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE wallet_nonces ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_wallet_nonces_expiry ON wallet_nonces (expires_at);
CREATE OR REPLACE FUNCTION purge_expired_wallet_nonces() RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_deleted integer; BEGIN DELETE FROM wallet_nonces WHERE expires_at < now(); GET DIAGNOSTICS v_deleted = ROW_COUNT; RETURN v_deleted; END; $fn$;
REVOKE ALL ON FUNCTION purge_expired_wallet_nonces() FROM PUBLIC;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'purge-wallet-nonces') THEN PERFORM cron.unschedule('purge-wallet-nonces'); END IF; PERFORM cron.schedule('purge-wallet-nonces', '17 * * * *', $cron$SELECT purge_expired_wallet_nonces()$cron$); END IF; END $$;

-- Migration 31: atomic message quota
CREATE OR REPLACE FUNCTION claim_message_quota(p_agent_id uuid, p_day_number integer, p_message_type text, p_limit integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_count integer; BEGIN INSERT INTO daily_message_counts (agent_id, day_number, message_type, count) VALUES (p_agent_id, p_day_number, p_message_type, 1) ON CONFLICT (agent_id, day_number, message_type) DO UPDATE SET count = daily_message_counts.count + 1 RETURNING count INTO v_count; IF v_count > p_limit THEN UPDATE daily_message_counts SET count = count - 1 WHERE agent_id = p_agent_id AND day_number = p_day_number AND message_type = p_message_type; RETURN jsonb_build_object('allowed', false, 'used', p_limit, 'limit', p_limit, 'remaining', 0); END IF; RETURN jsonb_build_object('allowed', true, 'used', v_count, 'limit', p_limit, 'remaining', GREATEST(p_limit - v_count, 0)); END; $fn$;
REVOKE ALL ON FUNCTION claim_message_quota(uuid, integer, text, integer) FROM PUBLIC, anon;
CREATE OR REPLACE FUNCTION release_message_quota(p_agent_id uuid, p_day_number integer, p_message_type text) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ UPDATE daily_message_counts SET count = GREATEST(count - 1, 0) WHERE agent_id = p_agent_id AND day_number = p_day_number AND message_type = p_message_type; $fn$;
REVOKE ALL ON FUNCTION release_message_quota(uuid, integer, text) FROM PUBLIC, anon;

-- Migration 32: fix grants + revoque functions + purchase_unlock v2 + notify whitelist
DO $$ DECLARE v_view text; BEGIN FOREACH v_view IN ARRAY ARRAY['agents_public','hints_public','host_public','events_feed','video_settings_public'] LOOP IF EXISTS (SELECT 1 FROM pg_views WHERE schemaname = 'public' AND viewname = v_view) THEN EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, anon, authenticated', v_view); EXECUTE format('GRANT SELECT ON public.%I TO anon, authenticated', v_view); END IF; END LOOP; END $$;
DO $$ DECLARE v_sig text; BEGIN FOREACH v_sig IN ARRAY ARRAY['advance_season_day(uuid, boolean)','close_season(uuid, text)','tick_all_seasons()','claim_message_quota(uuid, integer, text, integer)','release_message_quota(uuid, integer, text)','purge_expired_wallet_nonces()','notify_edge_function(text, jsonb)','prevent_role_self_escalation()'] LOOP BEGIN EXECUTE format('REVOKE ALL ON FUNCTION public.%s FROM PUBLIC, anon, authenticated', v_sig); EXCEPTION WHEN undefined_function THEN RAISE NOTICE 'Fonction absente: %', v_sig; END; END LOOP; END $$;
CREATE OR REPLACE FUNCTION notify_edge_function(fn_name text, payload jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp, net AS $fn$ DECLARE v_url text := current_setting('app.supabase_url', true); v_secret text := current_setting('app.cron_secret', true); BEGIN IF fn_name NOT IN ('auto-tick','daily-confessionals','generate-host-clue','process-video-jobs') THEN RAISE EXCEPTION 'Fonction non autorisee: %', fn_name; END IF; IF v_url IS NULL OR v_url = '' OR v_secret IS NULL OR v_secret = '' THEN RAISE WARNING 'notify_edge_function(%): non configure', fn_name; RETURN; END IF; PERFORM net.http_post(url := v_url || '/functions/v1/' || fn_name, headers := jsonb_build_object('Content-Type', 'application/json', 'X-Cron-Secret', v_secret), body := payload); EXCEPTION WHEN OTHERS THEN RAISE WARNING 'notify_edge_function(%) a echoue: %', fn_name, SQLERRM; END; $fn$;
REVOKE ALL ON FUNCTION notify_edge_function(text, jsonb) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION prevent_role_self_escalation() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $fn$ DECLARE v_jwt_role text; BEGIN IF current_user IN ('postgres', 'service_role', 'supabase_admin') THEN RETURN NEW; END IF; BEGIN v_jwt_role := current_setting('request.jwt.claims', true)::jsonb ->> 'role'; EXCEPTION WHEN OTHERS THEN v_jwt_role := NULL; END; IF v_jwt_role = 'service_role' THEN RETURN NEW; END IF; IF TG_OP = 'INSERT' THEN IF NEW.role NOT IN ('spectator', 'owner') THEN NEW.role := 'spectator'; END IF; RETURN NEW; END IF; IF NEW.role IS DISTINCT FROM OLD.role THEN RAISE EXCEPTION 'Le role ne peut pas etre modifie depuis le client'; END IF; RETURN NEW; END; $fn$;
DO $$ DECLARE r record; BEGIN FOR r IN SELECT c.conrelid::regclass::text AS tbl, c.conname FROM pg_constraint c WHERE c.contype = 'c' AND c.conrelid::regclass::text IN ('daily_message_counts','allowances_daily','influence_history','scoring_log','diary_entries') AND pg_get_constraintdef(c.oid) ILIKE '%day_number%' AND pg_get_constraintdef(c.oid) ILIKE '%7%' LOOP EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname); EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I CHECK (day_number >= 1)', r.tbl, r.conname); END LOOP; END $$;
CREATE OR REPLACE FUNCTION purchase_unlock(p_kind text, p_season_id uuid, p_target_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_season record; v_price numeric; v_credit numeric; v_require_confirmed boolean := COALESCE(current_setting('app.require_confirmed_payment', true)::boolean, false); BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; IF p_kind NOT IN ('dm', 'diary') THEN RETURN jsonb_build_object('ok', false, 'error', 'unknown_kind'); END IF; SELECT * INTO v_season FROM seasons WHERE id = p_season_id; IF v_season IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_found'); END IF; v_price := CASE p_kind WHEN 'dm' THEN COALESCE(v_season.dm_reveal_fee_usdc, 0) ELSE COALESCE(v_season.diary_unlock_fee_usdc, 0) END; IF p_kind = 'dm' AND EXISTS (SELECT 1 FROM dm_reveals WHERE user_id = v_user AND event_id = p_target_id) THEN RETURN jsonb_build_object('ok', true, 'already_unlocked', true); END IF; IF p_kind = 'diary' AND EXISTS (SELECT 1 FROM diary_unlocks WHERE user_id = v_user AND agent_id = p_target_id) THEN RETURN jsonb_build_object('ok', true, 'already_unlocked', true); END IF; IF v_require_confirmed AND v_price > 0 THEN SELECT COALESCE((SELECT SUM(amount_usdc) FROM payments WHERE user_id = v_user AND season_id = p_season_id AND status = 'confirmed' AND type = 'influence'), 0) - COALESCE((SELECT SUM(amount_usdc) FROM dm_reveals WHERE user_id = v_user AND season_id = p_season_id), 0) - COALESCE((SELECT SUM(amount_usdc) FROM diary_unlocks WHERE user_id = v_user AND season_id = p_season_id), 0) INTO v_credit; IF v_credit < v_price THEN RETURN jsonb_build_object('ok', false, 'error', 'payment_required', 'required', v_price, 'available', v_credit); END IF; ELSIF v_price > 0 THEN INSERT INTO payments (user_id, season_id, type, amount_usdc, status) VALUES (v_user, p_season_id, 'influence', v_price, 'pending'); END IF; IF p_kind = 'dm' THEN INSERT INTO dm_reveals (event_id, user_id, season_id, amount_usdc) VALUES (p_target_id, v_user, p_season_id, v_price); ELSE INSERT INTO diary_unlocks (user_id, agent_id, season_id, amount_usdc) VALUES (v_user, p_target_id, p_season_id, v_price); END IF; RETURN jsonb_build_object('ok', true, 'amount', v_price); END; $fn$;
REVOKE ALL ON FUNCTION purchase_unlock(text, uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION purchase_unlock(text, uuid, uuid) TO authenticated;
DO $$ DECLARE v_conname text; BEGIN SELECT conname INTO v_conname FROM pg_constraint WHERE conrelid = 'daily_message_counts'::regclass AND contype = 'c' AND pg_get_constraintdef(oid) ILIKE '%message_type%'; IF v_conname IS NOT NULL THEN EXECUTE format('ALTER TABLE daily_message_counts DROP CONSTRAINT %I', v_conname); END IF; END $$;
ALTER TABLE daily_message_counts ADD CONSTRAINT daily_message_counts_message_type_check CHECK (message_type IN ('public_chat', 'private_dm', 'confessional'));

-- Migration 33: admin season controls
CREATE OR REPLACE FUNCTION admin_advance_season_day(p_season_id uuid, p_force boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ BEGIN IF NOT EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin') THEN RETURN jsonb_build_object('ok', false, 'error', 'admin_required'); END IF; RETURN advance_season_day(p_season_id, p_force); END; $fn$;
CREATE OR REPLACE FUNCTION admin_close_season(p_season_id uuid, p_reason text DEFAULT 'adminClosed') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ BEGIN IF NOT EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin') THEN RETURN jsonb_build_object('ok', false, 'error', 'admin_required'); END IF; RETURN close_season(p_season_id, p_reason); END; $fn$;
REVOKE ALL ON FUNCTION admin_advance_season_day(uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION admin_close_season(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION admin_advance_season_day(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION admin_close_season(uuid, text) TO authenticated;
