/* # Migrations 43-52: spectator deduction, challenges, secret difficulty, wallet/models, billing, behavior dials, launch copies, welcome bonus, reset seasons, validate secret, cancel season */

-- Migration 43: spectator deduction
CREATE TABLE IF NOT EXISTS spectator_guesses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE, season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE CASCADE, day_number integer NOT NULL CHECK (day_number >= 1), guess text NOT NULL, correct boolean NOT NULL DEFAULT false, first_blood boolean NOT NULL DEFAULT false, points integer NOT NULL DEFAULT 0 CHECK (points >= 0), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (user_id, agent_id, day_number));
ALTER TABLE spectator_guesses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own guesses" ON spectator_guesses;
CREATE POLICY "Users read own guesses" ON spectator_guesses FOR SELECT TO authenticated USING (user_id = auth.uid() OR correct = true);
CREATE INDEX IF NOT EXISTS idx_guesses_season_user ON spectator_guesses (season_id, user_id);
CREATE INDEX IF NOT EXISTS idx_guesses_agent ON spectator_guesses (agent_id) WHERE correct = true;
CREATE OR REPLACE FUNCTION submit_spectator_guess(p_agent_id uuid, p_guess text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_agent record; v_season record; v_guess text; v_correct boolean; v_first boolean; v_points integer := 0; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; v_guess := btrim(COALESCE(p_guess, '')); IF v_guess = '' THEN RETURN jsonb_build_object('ok', false, 'error', 'empty_guess'); END IF; v_guess := left(v_guess, 60); SELECT * INTO v_agent FROM agents WHERE id = p_agent_id; IF v_agent IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_not_found'); END IF; SELECT * INTO v_season FROM seasons WHERE id = v_agent.season_id; IF v_season IS NULL OR v_season.status <> 'live' THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_live'); END IF; IF NOT v_agent.alive THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_eliminated'); END IF; IF v_agent.owner_user_id = v_user THEN RETURN jsonb_build_object('ok', false, 'error', 'own_agent'); END IF; IF EXISTS (SELECT 1 FROM spectator_guesses WHERE user_id = v_user AND agent_id = p_agent_id AND day_number = v_season.current_day) THEN RETURN jsonb_build_object('ok', false, 'error', 'already_guessed_today'); END IF; v_correct := normalize_secret(v_guess) <> '' AND normalize_secret(v_agent.secret_keyword) <> '' AND normalize_secret(v_guess) = normalize_secret(v_agent.secret_keyword); IF v_correct THEN v_first := NOT EXISTS (SELECT 1 FROM spectator_guesses WHERE agent_id = p_agent_id AND correct = true); v_points := CASE WHEN v_first THEN 25 ELSE 10 END; ELSE v_first := false; END IF; INSERT INTO spectator_guesses (user_id, agent_id, season_id, day_number, guess, correct, first_blood, points) VALUES (v_user, p_agent_id, v_agent.season_id, v_season.current_day, v_guess, v_correct, v_first, v_points); IF v_correct THEN INSERT INTO events (season_id, day_number, event_type, target_agent_id, actor_user_id, payload_json, visibility) VALUES (v_agent.season_id, v_season.current_day, 'system', p_agent_id, v_user, jsonb_build_object('message', 'Un spectateur a devine le secret de ' || v_agent.name || '.', 'kind', 'spectator_deduction', 'first_blood', v_first), 'public'); END IF; RETURN jsonb_build_object('ok', true, 'correct', v_correct, 'first_blood', v_first, 'points', v_points); END; $fn$;
REVOKE ALL ON FUNCTION submit_spectator_guess(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION submit_spectator_guess(uuid, text) TO authenticated;
CREATE OR REPLACE VIEW sleuth_leaderboard WITH (security_invoker = false) AS SELECT g.user_id, COALESCE(NULLIF(u.display_name, ''), u.username, 'Anonyme') AS display_name, SUM(g.points)::integer AS points, COUNT(*) FILTER (WHERE g.correct)::integer AS correct_guesses, COUNT(*) FILTER (WHERE g.first_blood)::integer AS first_bloods, COUNT(*)::integer AS attempts, MAX(g.created_at) AS last_guess_at FROM spectator_guesses g JOIN users u ON u.id = g.user_id GROUP BY g.user_id, u.display_name, u.username HAVING SUM(g.points) > 0;
REVOKE ALL ON sleuth_leaderboard FROM PUBLIC, anon, authenticated;
GRANT SELECT ON sleuth_leaderboard TO anon, authenticated;
CREATE OR REPLACE FUNCTION my_guesses(p_season_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_day integer; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; SELECT current_day INTO v_day FROM seasons WHERE id = p_season_id; RETURN jsonb_build_object('ok', true, 'day', v_day, 'points', COALESCE((SELECT SUM(points)::integer FROM spectator_guesses WHERE user_id = v_user AND season_id = p_season_id), 0), 'guessed_today', COALESCE((SELECT jsonb_agg(agent_id) FROM spectator_guesses WHERE user_id = v_user AND season_id = p_season_id AND day_number = v_day), '[]'::jsonb), 'cracked', COALESCE((SELECT jsonb_agg(agent_id) FROM spectator_guesses WHERE user_id = v_user AND season_id = p_season_id AND correct = true), '[]'::jsonb)); END; $fn$;
REVOKE ALL ON FUNCTION my_guesses(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION my_guesses(uuid) TO authenticated;

-- Migration 44: agent challenges
CREATE TABLE IF NOT EXISTS agent_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), token text NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(12), 'hex'), season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE CASCADE, from_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, from_config_id uuid NOT NULL REFERENCES agent_configs(id) ON DELETE CASCADE, message text NOT NULL DEFAULT '', accepted_count integer NOT NULL DEFAULT 0 CHECK (accepted_count >= 0), expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'), created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE agent_challenges ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_challenges_season ON agent_challenges (season_id);
CREATE OR REPLACE FUNCTION create_challenge(p_config_id uuid, p_max_agents integer DEFAULT 6, p_message text DEFAULT '') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_config record; v_season_id uuid; v_token text; v_max integer; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; SELECT * INTO v_config FROM agent_configs WHERE id = p_config_id AND owner_user_id = v_user; IF v_config IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_your_agent'); END IF; IF NOT v_config.ready THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_not_ready'); END IF; v_max := LEAST(GREATEST(COALESCE(p_max_agents, 6), 2), 12); INSERT INTO seasons (title, status, max_agents, max_agents_per_owner, current_day) VALUES (COALESCE(NULLIF(btrim(v_config.name), ''), 'Un agent') || ' lance un defi', 'draft', v_max, 1, 1) RETURNING id INTO v_season_id; INSERT INTO season_enrollments (season_id, agent_config_id, owner_user_id, status) VALUES (v_season_id, p_config_id, v_user, 'pending'); INSERT INTO agent_challenges (season_id, from_user_id, from_config_id, message) VALUES (v_season_id, v_user, p_config_id, left(btrim(COALESCE(p_message, '')), 240)) RETURNING token INTO v_token; RETURN jsonb_build_object('ok', true, 'token', v_token, 'season_id', v_season_id, 'max_agents', v_max); END; $fn$;
REVOKE ALL ON FUNCTION create_challenge(uuid, integer, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION create_challenge(uuid, integer, text) TO authenticated;
CREATE OR REPLACE FUNCTION view_challenge(p_token text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_ch record; v_season record; v_count integer; BEGIN SELECT * INTO v_ch FROM agent_challenges WHERE token = p_token; IF v_ch IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_found'); END IF; IF v_ch.expires_at < now() THEN RETURN jsonb_build_object('ok', false, 'error', 'expired'); END IF; SELECT * INTO v_season FROM seasons WHERE id = v_ch.season_id; SELECT COUNT(*) INTO v_count FROM season_enrollments WHERE season_id = v_ch.season_id AND COALESCE(status, 'accepted') <> 'rejected'; RETURN jsonb_build_object('ok', true, 'token', v_ch.token, 'season_id', v_ch.season_id, 'season_status', v_season.status, 'message', v_ch.message, 'max_agents', v_season.max_agents, 'enrolled', v_count, 'challenger', (SELECT jsonb_build_object('name', c.name, 'avatar_url', c.avatar_url, 'config_id', c.id, 'rating', c.rating) FROM agent_configs c WHERE c.id = v_ch.from_config_id)); END; $fn$;
REVOKE ALL ON FUNCTION view_challenge(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION view_challenge(text) TO anon, authenticated;
CREATE OR REPLACE FUNCTION accept_challenge(p_token text, p_config_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_ch record; v_season record; v_config record; v_count integer; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; SELECT * INTO v_ch FROM agent_challenges WHERE token = p_token FOR UPDATE; IF v_ch IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_found'); END IF; IF v_ch.expires_at < now() THEN RETURN jsonb_build_object('ok', false, 'error', 'expired'); END IF; SELECT * INTO v_season FROM seasons WHERE id = v_ch.season_id FOR UPDATE; IF v_season.status <> 'draft' THEN RETURN jsonb_build_object('ok', false, 'error', 'season_already_started', 'season_id', v_ch.season_id); END IF; SELECT * INTO v_config FROM agent_configs WHERE id = p_config_id AND owner_user_id = v_user; IF v_config IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_your_agent'); END IF; IF NOT v_config.ready THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_not_ready'); END IF; IF EXISTS (SELECT 1 FROM season_enrollments WHERE season_id = v_ch.season_id AND owner_user_id = v_user) THEN RETURN jsonb_build_object('ok', false, 'error', 'already_enrolled', 'season_id', v_ch.season_id); END IF; SELECT COUNT(*) INTO v_count FROM season_enrollments WHERE season_id = v_ch.season_id AND COALESCE(status, 'accepted') <> 'rejected'; IF v_count >= v_season.max_agents THEN RETURN jsonb_build_object('ok', false, 'error', 'season_full'); END IF; INSERT INTO season_enrollments (season_id, agent_config_id, owner_user_id, status) VALUES (v_ch.season_id, p_config_id, v_user, 'pending'); UPDATE agent_challenges SET accepted_count = accepted_count + 1 WHERE id = v_ch.id; RETURN jsonb_build_object('ok', true, 'season_id', v_ch.season_id, 'enrolled', v_count + 1, 'max_agents', v_season.max_agents); END; $fn$;
REVOKE ALL ON FUNCTION accept_challenge(text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION accept_challenge(text, uuid) TO authenticated;

-- Migration 45: secret difficulty
CREATE TABLE IF NOT EXISTS secret_blocklist (normalized text PRIMARY KEY, reason text NOT NULL DEFAULT 'cluster_historique', created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE secret_blocklist ENABLE ROW LEVEL SECURITY;
INSERT INTO secret_blocklist (normalized, reason) SELECT normalize_secret(w), 'cluster_historique' FROM unnest(ARRAY['eclipse','mirage','paradoxe','chimere','vertigo','obsidienne','nocturne','constellation','corbeau','flamme','echo','lune','bibliotheque','fantome','papillon','labyrinthe','crepuscule','aurore','silence','miroir','oracle','phenix','spectre','nebuleuse','solstice','abysse','zenith','penombre','orage']) AS w ON CONFLICT (normalized) DO NOTHING;
CREATE OR REPLACE FUNCTION secret_is_available(p_secret text, p_season_id uuid DEFAULT NULL, p_recent_days integer DEFAULT 90) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_norm text := normalize_secret(p_secret); BEGIN IF v_norm = '' OR length(v_norm) < 5 THEN RETURN jsonb_build_object('available', false, 'reason', 'too_short'); END IF; IF length(v_norm) > 24 THEN RETURN jsonb_build_object('available', false, 'reason', 'too_long'); END IF; IF EXISTS (SELECT 1 FROM secret_blocklist WHERE normalized = v_norm) THEN RETURN jsonb_build_object('available', false, 'reason', 'blocklisted'); END IF; IF p_season_id IS NOT NULL AND EXISTS (SELECT 1 FROM agents WHERE season_id = p_season_id AND normalize_secret(secret_keyword) = v_norm) THEN RETURN jsonb_build_object('available', false, 'reason', 'taken_in_season'); END IF; IF EXISTS (SELECT 1 FROM agents a JOIN seasons s ON s.id = a.season_id WHERE normalize_secret(a.secret_keyword) = v_norm AND s.created_at > now() - make_interval(days => p_recent_days)) THEN RETURN jsonb_build_object('available', false, 'reason', 'used_recently'); END IF; RETURN jsonb_build_object('available', true); END; $fn$;
REVOKE ALL ON FUNCTION secret_is_available(text, uuid, integer) FROM PUBLIC, anon, authenticated;
ALTER TABLE seasons ADD COLUMN IF NOT EXISTS hint_directness integer NOT NULL DEFAULT 1;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'seasons_hint_directness_range') THEN ALTER TABLE seasons ADD CONSTRAINT seasons_hint_directness_range CHECK (hint_directness BETWEEN 1 AND 2); END IF; END $$;
CREATE INDEX IF NOT EXISTS idx_agents_secret_norm ON agents (normalize_secret(secret_keyword));

-- Migration 46: wallet + llm_models + token_usage
CREATE TABLE IF NOT EXISTS wallet_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL CHECK (kind IN ('deposit','entry_fee','token_usage','refund','payout','adjustment')), amount_usdc numeric(18,6) NOT NULL, season_id uuid REFERENCES seasons(id) ON DELETE SET NULL, agent_id uuid REFERENCES agents(id) ON DELETE SET NULL, note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_ledger_user ON wallet_ledger (user_id, created_at DESC);
ALTER TABLE wallet_ledger ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own ledger" ON wallet_ledger;
CREATE POLICY "Users read own ledger" ON wallet_ledger FOR SELECT TO authenticated USING (user_id = auth.uid());
ALTER TABLE users ADD COLUMN IF NOT EXISTS balance_usdc numeric(18,6) NOT NULL DEFAULT 0;
CREATE OR REPLACE FUNCTION trg_wallet_apply() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ BEGIN UPDATE users SET balance_usdc = balance_usdc + NEW.amount_usdc WHERE id = NEW.user_id; RETURN NEW; END; $fn$;
DROP TRIGGER IF EXISTS trg_ledger_apply ON wallet_ledger;
CREATE TRIGGER trg_ledger_apply AFTER INSERT ON wallet_ledger FOR EACH ROW EXECUTE FUNCTION trg_wallet_apply();
CREATE TABLE IF NOT EXISTS llm_models (slug text PRIMARY KEY, label text NOT NULL, provider_model text NOT NULL, price_in_per_mtok numeric(12,6) NOT NULL DEFAULT 0 CHECK (price_in_per_mtok >= 0), price_out_per_mtok numeric(12,6) NOT NULL DEFAULT 0 CHECK (price_out_per_mtok >= 0), tier text NOT NULL DEFAULT 'standard' CHECK (tier IN ('gratuit','economique','standard','avance')), blurb text NOT NULL DEFAULT '', enabled boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 100, updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE llm_models ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read models" ON llm_models;
CREATE POLICY "Anyone can read models" ON llm_models FOR SELECT TO anon, authenticated USING (enabled = true);
INSERT INTO llm_models (slug, label, provider_model, price_in_per_mtok, price_out_per_mtok, tier, blurb, sort_order) VALUES ('gratuit','Recrue','meta-llama/llama-3.1-8b-instruct',0.00,0.00,'gratuit','Gratuit, sans frais. Repli automatique quand le solde est vide.',10), ('rapide','Tacticienne','openai/gpt-4o-mini',0.15,0.60,'economique','Bon rapport cout / finesse. Convient a la plupart des parties.',20), ('solide','Strategiste','anthropic/claude-3.5-haiku',0.80,4.00,'standard','Raisonne mieux sur les indices et les alliances.',30), ('elite','Maitresse','openai/gpt-4o',2.50,10.00,'avance','Deduction la plus fine. Consomme vite.',40) ON CONFLICT (slug) DO UPDATE SET label = EXCLUDED.label, provider_model = EXCLUDED.provider_model, tier = EXCLUDED.tier, blurb = EXCLUDED.blurb, sort_order = EXCLUDED.sort_order, updated_at = now();
ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS model_slug text NOT NULL DEFAULT 'rapide' REFERENCES llm_models(slug) ON UPDATE CASCADE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS model_slug text NOT NULL DEFAULT 'rapide' REFERENCES llm_models(slug) ON UPDATE CASCADE;
CREATE TABLE IF NOT EXISTS token_usage (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, agent_id uuid REFERENCES agents(id) ON DELETE SET NULL, season_id uuid REFERENCES seasons(id) ON DELETE SET NULL, model_slug text NOT NULL, prompt_tokens integer NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0), output_tokens integer NOT NULL DEFAULT 0 CHECK (output_tokens >= 0), cost_usdc numeric(18,6) NOT NULL DEFAULT 0, charged_usdc numeric(18,6) NOT NULL DEFAULT 0, downgraded boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_usage_user ON token_usage (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_usage_agent ON token_usage (agent_id, created_at DESC);
ALTER TABLE token_usage ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own usage" ON token_usage;
CREATE POLICY "Users read own usage" ON token_usage FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE OR REPLACE FUNCTION token_margin() RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp AS $fn$ SELECT COALESCE(NULLIF(current_setting('app.token_margin', true), '')::numeric, 3.0); $fn$;
GRANT EXECUTE ON FUNCTION token_margin() TO anon, authenticated;

-- Migration 47: billing functions
CREATE OR REPLACE FUNCTION resolve_agent_model(p_agent_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_agent record; v_model record; v_balance numeric; v_reserve numeric := 0.05; BEGIN SELECT a.id, a.model_slug, a.owner_user_id, a.season_id INTO v_agent FROM agents a WHERE a.id = p_agent_id; IF v_agent IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_not_found'); END IF; SELECT * INTO v_model FROM llm_models WHERE slug = v_agent.model_slug AND enabled = true; IF v_model IS NULL THEN SELECT * INTO v_model FROM llm_models WHERE tier = 'gratuit' AND enabled = true ORDER BY sort_order LIMIT 1; END IF; SELECT balance_usdc INTO v_balance FROM users WHERE id = v_agent.owner_user_id; IF v_model.price_in_per_mtok = 0 AND v_model.price_out_per_mtok = 0 THEN RETURN jsonb_build_object('ok', true, 'slug', v_model.slug, 'provider_model', v_model.provider_model, 'downgraded', false); END IF; IF COALESCE(v_balance, 0) < v_reserve THEN SELECT * INTO v_model FROM llm_models WHERE tier = 'gratuit' AND enabled = true ORDER BY sort_order LIMIT 1; IF v_model IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'no_free_model'); END IF; RETURN jsonb_build_object('ok', true, 'slug', v_model.slug, 'provider_model', v_model.provider_model, 'downgraded', true, 'reason', 'insufficient_balance'); END IF; RETURN jsonb_build_object('ok', true, 'slug', v_model.slug, 'provider_model', v_model.provider_model, 'downgraded', false); END; $fn$;
REVOKE ALL ON FUNCTION resolve_agent_model(uuid) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION charge_tokens(p_agent_id uuid, p_model_slug text, p_prompt_tokens integer, p_output_tokens integer, p_downgraded boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_agent record; v_model record; v_cost numeric; v_charged numeric; v_balance numeric; BEGIN SELECT a.id, a.owner_user_id, a.season_id INTO v_agent FROM agents a WHERE a.id = p_agent_id; IF v_agent IS NULL OR v_agent.owner_user_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'agent_not_found'); END IF; SELECT * INTO v_model FROM llm_models WHERE slug = p_model_slug; IF v_model IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'unknown_model'); END IF; v_cost := COALESCE(p_prompt_tokens, 0)::numeric / 1000000 * v_model.price_in_per_mtok + COALESCE(p_output_tokens, 0)::numeric / 1000000 * v_model.price_out_per_mtok; v_charged := ROUND(v_cost * token_margin(), 6); INSERT INTO token_usage (user_id, agent_id, season_id, model_slug, prompt_tokens, output_tokens, cost_usdc, charged_usdc, downgraded) VALUES (v_agent.owner_user_id, p_agent_id, v_agent.season_id, p_model_slug, COALESCE(p_prompt_tokens, 0), COALESCE(p_output_tokens, 0), ROUND(v_cost, 6), v_charged, p_downgraded); IF v_charged > 0 THEN INSERT INTO wallet_ledger (user_id, kind, amount_usdc, season_id, agent_id, note) VALUES (v_agent.owner_user_id, 'token_usage', -v_charged, v_agent.season_id, p_agent_id, v_model.label); END IF; SELECT balance_usdc INTO v_balance FROM users WHERE id = v_agent.owner_user_id; RETURN jsonb_build_object('ok', true, 'cost', ROUND(v_cost, 6), 'charged', v_charged, 'balance', v_balance); END; $fn$;
REVOKE ALL ON FUNCTION charge_tokens(uuid, text, integer, integer, boolean) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION pay_entry_fee(p_season_id uuid, p_config_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_season record; v_balance numeric; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; SELECT * INTO v_season FROM seasons WHERE id = p_season_id FOR UPDATE; IF v_season IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_found'); END IF; IF NOT EXISTS (SELECT 1 FROM agent_configs WHERE id = p_config_id AND owner_user_id = v_user) THEN RETURN jsonb_build_object('ok', false, 'error', 'not_your_agent'); END IF; IF EXISTS (SELECT 1 FROM wallet_ledger WHERE user_id = v_user AND season_id = p_season_id AND kind = 'entry_fee') THEN RETURN jsonb_build_object('ok', true, 'already_paid', true); END IF; IF COALESCE(v_season.entry_fee_usdc, 0) <= 0 THEN RETURN jsonb_build_object('ok', true, 'amount', 0); END IF; SELECT balance_usdc INTO v_balance FROM users WHERE id = v_user FOR UPDATE; IF COALESCE(v_balance, 0) < v_season.entry_fee_usdc THEN RETURN jsonb_build_object('ok', false, 'error', 'insufficient_balance', 'required', v_season.entry_fee_usdc, 'balance', COALESCE(v_balance, 0)); END IF; INSERT INTO wallet_ledger (user_id, kind, amount_usdc, season_id, note) VALUES (v_user, 'entry_fee', -v_season.entry_fee_usdc, p_season_id, 'Droit d''entree ' || v_season.title); UPDATE seasons SET prize_pool_usdc = prize_pool_usdc + v_season.entry_fee_usdc WHERE id = p_season_id; RETURN jsonb_build_object('ok', true, 'amount', v_season.entry_fee_usdc); END; $fn$;
REVOKE ALL ON FUNCTION pay_entry_fee(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION pay_entry_fee(uuid, uuid) TO authenticated;
CREATE OR REPLACE FUNCTION my_wallet() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; RETURN jsonb_build_object('ok', true, 'balance', COALESCE((SELECT balance_usdc FROM users WHERE id = v_user), 0), 'spent_tokens', COALESCE((SELECT SUM(charged_usdc) FROM token_usage WHERE user_id = v_user), 0), 'calls', COALESCE((SELECT COUNT(*) FROM token_usage WHERE user_id = v_user), 0), 'recent', COALESCE((SELECT jsonb_agg(jsonb_build_object('kind', l.kind, 'amount', l.amount_usdc, 'note', l.note, 'at', l.created_at) ORDER BY l.created_at DESC) FROM (SELECT * FROM wallet_ledger WHERE user_id = v_user ORDER BY created_at DESC LIMIT 20) l), '[]'::jsonb)); END; $fn$;
REVOKE ALL ON FUNCTION my_wallet() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION my_wallet() TO authenticated;

-- Migration 48: behavior dials
ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS trait_audace integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_sociabilite integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_expressivite integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_introspection integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_loyaute integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_discretion integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS signature_style text NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS taboo text NOT NULL DEFAULT '';
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['trait_audace','trait_sociabilite','trait_expressivite','trait_introspection','trait_loyaute','trait_discretion'] LOOP IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_configs_' || c || '_range') THEN EXECUTE format('ALTER TABLE agent_configs ADD CONSTRAINT %I CHECK (%I BETWEEN 0 AND 100)', 'agent_configs_' || c || '_range', c); END IF; END LOOP; END $$;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS trait_audace integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_sociabilite integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_expressivite integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_introspection integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_loyaute integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS trait_discretion integer NOT NULL DEFAULT 50, ADD COLUMN IF NOT EXISTS signature_style text NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS taboo text NOT NULL DEFAULT '';
CREATE OR REPLACE FUNCTION scale_trait(p_value integer) RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp AS $fn$ SELECT CASE WHEN COALESCE(p_value, 50) <= 50 THEN 0.33 + (COALESCE(p_value, 50)::numeric / 50) * 0.67 ELSE 1.0 + ((COALESCE(p_value, 50) - 50)::numeric / 50) END; $fn$;
GRANT EXECUTE ON FUNCTION scale_trait(integer) TO anon, authenticated;
CREATE OR REPLACE FUNCTION agent_action_weights(p_agent_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE a record; BEGIN SELECT trait_audace, trait_sociabilite, trait_expressivite, trait_introspection INTO a FROM agents WHERE id = p_agent_id; IF a IS NULL THEN RETURN jsonb_build_object('accusation', 10, 'public_chat', 45, 'confessional', 20, 'dm', 25); END IF; RETURN jsonb_build_object('accusation', ROUND(10 * scale_trait(a.trait_audace)), 'public_chat', ROUND(45 * scale_trait(a.trait_expressivite)), 'confessional', ROUND(20 * scale_trait(a.trait_introspection)), 'dm', ROUND(25 * scale_trait(a.trait_sociabilite))); END; $fn$;
REVOKE ALL ON FUNCTION agent_action_weights(uuid) FROM PUBLIC, anon, authenticated;

-- Migration 49: launch copies traits + model
CREATE OR REPLACE FUNCTION auto_launch_season_when_full() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_season record; v_enrolled_count integer; v_enr record; v_cfg record; v_agent_id uuid; v_prize_pool numeric; v_updated integer; BEGIN SELECT * INTO v_season FROM seasons WHERE id = NEW.season_id AND status = 'draft' FOR UPDATE; IF v_season IS NULL THEN RETURN NEW; END IF; SELECT COUNT(*) INTO v_enrolled_count FROM season_enrollments WHERE season_id = NEW.season_id AND COALESCE(status, 'accepted') <> 'rejected'; IF v_enrolled_count < v_season.max_agents THEN RETURN NEW; END IF; v_prize_pool := GREATEST(v_season.max_agents * v_season.entry_fee_usdc * (1.0 - v_season.platform_fee_pct::numeric / 100.0), COALESCE(v_season.prize_pool_usdc, 0)); FOR v_enr IN SELECT * FROM season_enrollments WHERE season_id = NEW.season_id AND COALESCE(status, 'accepted') <> 'rejected' LOOP IF EXISTS (SELECT 1 FROM agents WHERE season_id = NEW.season_id AND agent_config_id = v_enr.agent_config_id) THEN CONTINUE; END IF; SELECT * INTO v_cfg FROM agent_configs WHERE id = v_enr.agent_config_id; IF v_cfg IS NULL THEN CONTINUE; END IF; INSERT INTO agents (season_id, owner_user_id, agent_config_id, name, avatar_url, llm_provider, llm_model, model_slug, secret_keyword, presentation, alive, popularity, reputation, owner_influences_remaining, confessional_count, api_key, trait_audace, trait_sociabilite, trait_expressivite, trait_introspection, trait_loyaute, trait_discretion, signature_style, taboo) VALUES (NEW.season_id, v_enr.owner_user_id, v_enr.agent_config_id, v_cfg.name, v_cfg.avatar_url, 'openrouter', v_cfg.openrouter_model, COALESCE(v_cfg.model_slug, 'rapide'), normalize_secret(v_cfg.secret_keyword), COALESCE(v_cfg.presentation, ''), true, 50, 50, 2, 0, encode(gen_random_bytes(16), 'hex'), COALESCE(v_cfg.trait_audace, 50), COALESCE(v_cfg.trait_sociabilite, 50), COALESCE(v_cfg.trait_expressivite, 50), COALESCE(v_cfg.trait_introspection, 50), COALESCE(v_cfg.trait_loyaute, 50), COALESCE(v_cfg.trait_discretion, 50), COALESCE(v_cfg.signature_style, ''), COALESCE(v_cfg.taboo, '')) RETURNING id INTO v_agent_id; INSERT INTO hints (agent_id, level, hint_text, unlocked) VALUES (v_agent_id, 1, v_cfg.hint_1, false), (v_agent_id, 2, v_cfg.hint_2, false), (v_agent_id, 3, v_cfg.hint_3, false); END LOOP; UPDATE seasons SET status = 'live', started_at = now(), day_started_at = now(), current_day = 1, prize_pool_usdc = v_prize_pool WHERE id = NEW.season_id AND status = 'draft'; GET DIAGNOSTICS v_updated = ROW_COUNT; IF v_updated > 0 THEN PERFORM notify_edge_function('auto-tick', jsonb_build_object('trigger', 'season_launch', 'season_id', NEW.season_id)); END IF; RETURN NEW; END; $fn$;
DROP TRIGGER IF EXISTS trigger_auto_launch_season ON season_enrollments;
CREATE TRIGGER trigger_auto_launch_season AFTER INSERT ON season_enrollments FOR EACH ROW EXECUTE FUNCTION auto_launch_season_when_full();

-- Migration 50: welcome bonus
CREATE OR REPLACE FUNCTION welcome_bonus_amount() RETURNS numeric LANGUAGE sql STABLE SET search_path = public, pg_temp AS $fn$ SELECT COALESCE(NULLIF(current_setting('app.welcome_bonus', true), '')::numeric, 200); $fn$;
GRANT EXECUTE ON FUNCTION welcome_bonus_amount() TO anon, authenticated;
CREATE OR REPLACE FUNCTION grant_welcome_bonus(p_user_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_amount numeric := welcome_bonus_amount(); BEGIN IF v_amount <= 0 THEN RETURN false; END IF; IF EXISTS (SELECT 1 FROM wallet_ledger WHERE user_id = p_user_id AND kind = 'deposit' AND note = 'Bonus de bienvenue') THEN RETURN false; END IF; INSERT INTO wallet_ledger (user_id, kind, amount_usdc, note) VALUES (p_user_id, 'deposit', v_amount, 'Bonus de bienvenue'); RETURN true; END; $fn$;
REVOKE ALL ON FUNCTION grant_welcome_bonus(uuid) FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE FUNCTION trg_welcome_bonus() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ BEGIN PERFORM grant_welcome_bonus(NEW.id); RETURN NEW; END; $fn$;
DROP TRIGGER IF EXISTS trg_users_welcome_bonus ON users;
CREATE TRIGGER trg_users_welcome_bonus AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION trg_welcome_bonus();
DO $$ DECLARE u record; v_count integer := 0; BEGIN FOR u IN SELECT id FROM users LOOP IF grant_welcome_bonus(u.id) THEN v_count := v_count + 1; END IF; END LOOP; RAISE NOTICE 'Bonus de bienvenue accorde a % compte(s)', v_count; END $$;

-- Migration 51: reset seasons
CREATE OR REPLACE FUNCTION reset_all_seasons(p_include_ended boolean DEFAULT true) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_refunded integer := 0; v_amount numeric := 0; v_deleted integer := 0; r record; BEGIN FOR r IN SELECT l.user_id, l.season_id, -l.amount_usdc AS amount, s.title FROM wallet_ledger l JOIN seasons s ON s.id = l.season_id WHERE l.kind = 'entry_fee' AND l.amount_usdc < 0 AND s.status <> 'ended' AND NOT EXISTS (SELECT 1 FROM wallet_ledger r2 WHERE r2.user_id = l.user_id AND r2.season_id = l.season_id AND r2.kind = 'refund') LOOP INSERT INTO wallet_ledger (user_id, kind, amount_usdc, season_id, note) VALUES (r.user_id, 'refund', r.amount, r.season_id, 'Saison annulee : ' || COALESCE(r.title, 'sans titre')); v_refunded := v_refunded + 1; v_amount := v_amount + r.amount; END LOOP; IF p_include_ended THEN DELETE FROM seasons; ELSE DELETE FROM seasons WHERE status <> 'ended'; END IF; GET DIAGNOSTICS v_deleted = ROW_COUNT; RETURN jsonb_build_object('ok', true, 'seasons_deleted', v_deleted, 'refunds', v_refunded, 'refunded_total', v_amount); END; $fn$;
REVOKE ALL ON FUNCTION reset_all_seasons(boolean) FROM PUBLIC, anon, authenticated;
DO $$ DECLARE v_cleared integer; BEGIN UPDATE agent_configs SET secret_keyword = '', hint_1 = '', hint_2 = '', hint_3 = '', ready = false WHERE normalize_secret(secret_keyword) IN (SELECT normalized FROM secret_blocklist); GET DIAGNOSTICS v_cleared = ROW_COUNT; RAISE NOTICE 'Secrets obsoletes effaces sur % configuration(s)', v_cleared; END $$;
DO $$ DECLARE v_result jsonb; BEGIN v_result := reset_all_seasons(true); RAISE NOTICE 'Reinitialisation: %', v_result; END $$;

-- Migration 52: validate secret on enroll
CREATE OR REPLACE FUNCTION trg_validate_enrollment_secret() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_cfg record; v_verdict jsonb; BEGIN SELECT secret_keyword, hint_1, hint_2, hint_3, name INTO v_cfg FROM agent_configs WHERE id = NEW.agent_config_id; IF v_cfg IS NULL THEN RAISE EXCEPTION 'Configuration d''agent introuvable'; END IF; IF COALESCE(btrim(v_cfg.hint_1), '') = '' OR COALESCE(btrim(v_cfg.hint_2), '') = '' OR COALESCE(btrim(v_cfg.hint_3), '') = '' THEN RAISE EXCEPTION 'Les trois indices de « % » doivent etre renseignes avant l''inscription.', COALESCE(v_cfg.name, 'cet agent'); END IF; v_verdict := secret_is_available(v_cfg.secret_keyword, NEW.season_id); IF NOT (v_verdict->>'available')::boolean THEN RAISE EXCEPTION 'Le secret de « % » ne convient pas (%). Regenerez-le avant de vous inscrire.', COALESCE(v_cfg.name, 'cet agent'), COALESCE(v_verdict->>'reason', 'indisponible'); END IF; RETURN NEW; END; $fn$;
DROP TRIGGER IF EXISTS trg_enrollment_validate_secret ON season_enrollments;
CREATE TRIGGER trg_enrollment_validate_secret BEFORE INSERT ON season_enrollments FOR EACH ROW EXECUTE FUNCTION trg_validate_enrollment_secret();

-- Migration 52b: cancel season
CREATE OR REPLACE FUNCTION cancel_season(p_season_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$ DECLARE v_user uuid := auth.uid(); v_season record; v_refunded integer := 0; v_total numeric := 0; r record; BEGIN IF v_user IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated'); END IF; IF NOT EXISTS (SELECT 1 FROM users WHERE id = v_user AND role = 'admin') THEN RETURN jsonb_build_object('ok', false, 'error', 'admin_required'); END IF; SELECT * INTO v_season FROM seasons WHERE id = p_season_id FOR UPDATE; IF v_season IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'season_not_found'); END IF; IF v_season.status = 'ended' THEN RETURN jsonb_build_object('ok', false, 'error', 'season_ended'); END IF; FOR r IN SELECT l.user_id, -l.amount_usdc AS amount FROM wallet_ledger l WHERE l.season_id = p_season_id AND l.kind = 'entry_fee' AND l.amount_usdc < 0 AND NOT EXISTS (SELECT 1 FROM wallet_ledger r2 WHERE r2.user_id = l.user_id AND r2.season_id = p_season_id AND r2.kind = 'refund') LOOP INSERT INTO wallet_ledger (user_id, kind, amount_usdc, season_id, note) VALUES (r.user_id, 'refund', r.amount, p_season_id, 'Saison annulee : ' || COALESCE(v_season.title, 'sans titre')); v_refunded := v_refunded + 1; v_total := v_total + r.amount; END LOOP; DELETE FROM seasons WHERE id = p_season_id; RETURN jsonb_build_object('ok', true, 'title', v_season.title, 'refunds', v_refunded, 'refunded_total', v_total); END; $fn$;
REVOKE ALL ON FUNCTION cancel_season(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION cancel_season(uuid) TO authenticated;
